**Introduction**

**NumPy (Numerical Python)** is an open-source Python library used for working with numerical data.

NumPy is the foundation that many other major libraries are built on top of — like Pandas (data analysis), Matplotlib (plotting), SciPy (scientific computing), and even machine learning frameworks like TensorFlow and PyTorch.
It provides:

-Fast multidimensional arrays

-Mathematical operations

-Linear algebra

-Statistics

-Random number generation

-Reshaping, slicing, and indexing data efficiently


**Installation**

In [ ]:
pip install numpy

**Importing NumPy**

In [ ]:
import numpy as np

**1. Creating Arrays**

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])   #1D array
print(a)                   
print(type(a))               # <class 'numpy.ndarray'>

# 2D array (matrix)
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

# Handy generators
np.zeros((2, 3))     # 2x3 array of zeros
np.ones((3, 3))       # 3x3 array of ones
np.arange(0, 10, 2)   # [0 2 4 6 8]  -- like range()
np.linspace(0, 1, 5)  # [0. 0.25 0.5 0.75 1.]  -- 5 evenly spaced points
np.random.rand(2, 2)  # 2x2 random values between 0 and 1

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


array([[0.58342537, 0.73807327],
       [0.73638337, 0.92908007]])

**2. Array Properties**

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.shape)   # (2, 3) -- rows, columns
print(a.ndim)     # 2 -- number of dimensions
print(a.size)     # 6 -- total elements
print(a.dtype)    # int64 -- data type

(2, 3)
2
6
int64


**3. Indexing & Slicing**

In [4]:
a = np.array([10, 20, 30, 40, 50])
print(a[1])       
print(a[1:4])       
print(a[-1])        
print(a[::-1])    #reverse array

b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[0, 1])      # 2       -- row 0, col 1
print(b[:, 1])       # [2 5 8]  -- entire column 1
print(b[1, :])        # [4 5 6]  -- entire row 1

20
[20 30 40]
50
[50 40 30 20 10]
2
[2 5 8]
[4 5 6]


**4. Useful Aggregate Functions**

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.sum())        # 21
print(a.mean())        # 3.5
print(a.max())          # 6
print(a.sum(axis=0))     # [5 7 9]   -- sum down each column
print(a.sum(axis=1))     # [6 15]     -- sum across each row

21
3.5
6
[5 7 9]
[ 6 15]


**5. Broadcasting**

Expand small array to match the shape of larger array.

In [6]:
a = np.array([1, 2, 3])
print(a + 5)    # [6 7 8]  -- scalar "broadcasts" to every element

b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([10, 20, 30])
print(b + c)
# [[11 22 33]
#  [14 25 36]]   -- c is broadcast across each row

[6 7 8]
[[11 22 33]
 [14 25 36]]


**6. Linear Algebra (np.linalg)**

In [7]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A @ B)                 # matrix multiplication
print(np.linalg.inv(A))       # inverse
print(np.linalg.det(A))        # determinant
print(np.linalg.eig(A))         # eigenvalues & eigenvectors
print(np.linalg.solve(A, [1,2])) # solve Ax = b

[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
[0.  0.5]


**7. Random Module**

In [8]:
np.random.seed(42)              # reproducibility

np.random.rand(3)                 # 3 uniform randoms [0,1)
np.random.randn(3)                 # 3 from standard normal distribution
np.random.randint(1, 10, size=5)    # 5 random ints between 1-9
np.random.choice([10,20,30], size=2) # random pick from array
np.random.shuffle(a)                  # shuffles array in place

**8. Set Operations**

In [11]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print(np.union1d(a, b))          # [1 2 3 4 5 6]
print(np.intersect1d(a, b))        # [3 4]
print(np.setdiff1d(a, b))            # [1 2]  -- in a, not in b

print(np.isin(a, b))                 

[1 2 3 4 5 6]
[3 4]
[1 2]
[False False  True  True]


**9. Mathematical Operations**

In [12]:
a = np.array([1, 4, 9])

np.sqrt(a)        # [1. 2. 3.]
np.exp(a)          # e^x for each element
np.log(a)           # natural log
np.abs([-1, -2])     # [1 2]
np.round(3.14159, 2)  # 3.14
np.sin(a); np.cos(a)   # trig functions

array([ 0.54030231, -0.65364362, -0.91113026])

**10. Array Manipulation**

In [13]:
a = np.array([[1, 2], [3, 4]])

np.transpose(a)          # swap rows/cols  (or a.T)
np.concatenate([a, a])     # stack along axis 0
np.vstack([a, a])           # stack vertically
np.hstack([a, a])            # stack horizontally
np.split(a, 2)                 # split into 2 arrays

[array([[1, 2]]), array([[3, 4]])]

**11. append / insert / delete**

In [14]:
a = np.array([1, 4, 9])

np.sqrt(a)        # [1. 2. 3.]
np.exp(a)          # e^x for each element
np.log(a)           # natural log
np.abs([-1, -2])     # [1 2]
np.round(3.14159, 2)  # 3.14
np.sin(a); np.cos(a)   # trig functions

array([ 0.54030231, -0.65364362, -0.91113026])

**12. Where, reshape ,flatten**

In [15]:
#where
a = np.array([1, 2, 3, 4, 5])

print(np.where(a > 2))            
print(np.where(a > 2, a, 0))      

#reshape
a = np.arange(12)          # [0 1 2 ... 11]
b = a.reshape(3, 4)          # reshape into 3x4
print(b)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

a.reshape(-1, 2)   # -1 means "figure this dimension out automatically"

#flatten

b = np.array([[1, 2], [3, 4]])

print(b.flatten())   # [1 2 3 4]  -- returns a copy
print(b.ravel())       # [1 2 3 4]  -- returns a view (faster, but shares memory)

(array([2, 3, 4]),)
[0 0 3 4 5]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 2 3 4]
[1 2 3 4]
